# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 567f36be2991da953e36cc2a89f4ffea818504a8e5f3b8efe8a240747568cb0f7ccb7851fa38624bf9f9669795e16158cd92d12962c667b6bcc5ca7814214a15

test:
  secret_key_base: 2d37c591970e6acd2f9733cee225946f6126339992560b84f806b701d23533b15cf945357fb40cec169357af89c2265da938db8cb4cf46338d0faaf77ace38e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
